export enum CodigoErro {
  VALIDACAO = 'VALIDACAO',
  NAO_AUTENTICADO = 'NAO_AUTENTICADO',
  SEM_PERMISSAO = 'SEM_PERMISSAO',
  NAO_ENCONTRADO = 'NAO_ENCONTRADO',
  MATRICULA_DUPLICADA = 'MATRICULA_DUPLICADA',
  CODIGO_CHAVE_DUPLICADO = 'CODIGO_CHAVE_DUPLICADO',
  CHAVE_INDISPONIVEL = 'CHAVE_INDISPONIVEL',
  SOLICITANTE_INATIVO = 'SOLICITANTE_INATIVO',
  EMPRESTIMO_JA_DEVOLVIDO = 'EMPRESTIMO_JA_DEVOLVIDO',
  RECURSO_COM_EMPRESTIMO_ATIVO = 'RECURSO_COM_EMPRESTIMO_ATIVO',
  ERRO_INTERNO = 'ERRO_INTERNO',
}
