services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - .:/backend:/backend
      - node_modules:/backend/node_modules
    env_file:
      - backend/.env
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  

volumes:
  node_modules:
  db_data: